// Generated by ReScript, PLEASE EDIT WITH CARE


import { animated } from 'react-spring'
;

var make = animated.div;

var Div = {
  make: make
};

var Animated = {
  Div: Div
};

export {
  Animated ,
  
}
/*  Not a pure module */
