// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import LogoSvg from "./logo.svg";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.bs.js";
import * as Main$AppTemplateReasonReact from "./Main.bs.js";
import * as Redirect$AppTemplateReasonReact from "./Redirect.bs.js";
import * as LocaleContext$AppTemplateReasonReact from "./LocaleContext.bs.js";

var logo = LogoSvg;

function App$Routes(Props) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = url.path;
  if (match) {
    if (match.tl) {
      return React.createElement(Redirect$AppTemplateReasonReact.make, {
                  path: "/"
                });
    } else {
      return React.createElement(Main$AppTemplateReasonReact.make, {});
    }
  } else {
    return React.createElement(Main$AppTemplateReasonReact.make, {});
  }
}

var Routes = {
  make: App$Routes
};

function App(Props) {
  return React.createElement(LocaleContext$AppTemplateReasonReact.Provider.make, {
              children: React.createElement(App$Routes, {})
            });
}

var make = App;

export {
  logo ,
  Routes ,
  make ,
  
}
/* logo Not a pure module */
