// Generated by ReScript, PLEASE EDIT WITH CARE


function cx(arr) {
  var result = "";
  for(var i = 0 ,i_finish = arr.length; i < i_finish; ++i){
    var name = arr[i];
    if (name !== undefined && name !== "") {
      result = result === "" ? name : result + " " + name;
    }
    
  }
  return result;
}

export {
  cx ,
  
}
/* No side effect */
