// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as ReactSpring from "react-spring";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.bs.js";
import MainModuleScss from "./styles/Main.module.scss";
import * as CX$AppTemplateReasonReact from "./CX.bs.js";
import * as RSpring$AppTemplateReasonReact from "./Interop/RSpring.bs.js";

var styles = MainModuleScss;

var name = "Video Edit";

function Main(Props) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var transitions = ReactSpring.useTransition(url, {
        from: {
          opacity: "0",
          transform: "scale(1.1)"
        },
        enter: {
          opacity: "1",
          transform: "scale(1)"
        },
        leave: {
          opacity: "0"
        },
        config: {
          duration: 200
        }
      });
  React.useEffect((function () {
          var match = url.path;
          if (match) {
            switch (match.hd) {
              case "about" :
                  if (match.tl) {
                    document.title = name;
                  } else {
                    document.title = name + " — About";
                  }
                  break;
              case "deal" :
                  if (match.tl) {
                    document.title = name;
                  } else {
                    document.title = name + " — Experience";
                  }
                  break;
              default:
                document.title = name;
            }
          } else {
            document.title = name;
          }
          
        }), [url]);
  return React.createElement("div", {
              className: styles.base
            }, React.createElement("header", {
                  className: styles.header
                }, React.createElement("div", undefined)), React.createElement("main", {
                  className: CX$AppTemplateReasonReact.cx([
                        styles.content,
                        "full-size"
                      ])
                }, React.createElement("div", {
                      className: styles.body
                    }, Curry._1(transitions, (function (style, item) {
                            return React.createElement(RSpring$AppTemplateReasonReact.Animated.Div.make, {
                                        style: style,
                                        className: "page",
                                        children: React.createElement("div", undefined)
                                      });
                          }))), React.createElement("div", {
                      className: styles["in-dev"]
                    }, "Still development")));
}

var make = Main;

export {
  styles ,
  name ,
  make ,
  
}
/* styles Not a pure module */
