// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.bs.js";

function Redirect(Props) {
  var path = Props.path;
  React.useEffect((function () {
          RescriptReactRouter.replace(path);
          
        }), [path]);
  return null;
}

var make = Redirect;

export {
  make ,
  
}
/* react Not a pure module */
